### PR TITLE
Add announcement about namespace change to ReadMe

### PR DESCRIPTION
**Pull request by zvirja**
Adding an announcement about the changed default namespace. That should help our users to quickly find information why compilation failed after the update to v2 and what to do.

@moodmosaic @adamchester @jwChung Please take a look and suggest whether you see how to improve the message.

### CODE REVIEW

**Review by moodmosaic — CHANGES_REQUESTED** [review]
See https://github.com/AlbedoOrg/Albedo/pull/98.

**Review by moodmosaic — COMMENTED** [review]
Oh, you're mentioning version 2. Sorry about that. I'll just submit general feedback without explicit approval, then, until the path forward is clear 👍

**Review by moodmosaic — APPROVED** [review]
See https://github.com/AlbedoOrg/Albedo/pull/98#issuecomment-333388534.

**Comment by zvirja** [comment]
@adamchester @jwChung Could you please briefly check this one whether you have any concerns, so I can go ahead and trigger the release? PR is really tiny.

**Comment by zvirja** [comment]
@adamchester @jwChung To not block the AutoFixture (as I'll need to consume this package there) I'm going to merge this one given that Nikos has already approved the PR. Let's wait for yet another day and see whether you have any concerns. If not (or your will not reply) - I'll proceed further. Notice, we can always adjust the message after the PR is merged, so it shouldn't be a big problem.

**Review by adamchester — APPROVED** [review]

**Comment by zvirja** [comment]
Thanks @adamchester. I'm considering 2 approvals as enough to proceed further and merge the PR 😉
